=== Geneabase/Geneabase-XML/2013-v1/archive.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright Â© 2011-2013 Geneabase BV. Licenced under CC BY 3.0 http://creativecommons.org/licenses/by/3.0/ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:col="http://schemas.geneabase.com/2013-v1/archive"
    xmlns:gb="http://schemas.geneabase.com/2013-v1/geneabase"
    xmlns:html="http://www.w3.org/1999/xhtml" xmlns:xml="http://www.w3.org/XML/1998/namespace"
    targetNamespace="http://schemas.geneabase.com/2013-v1/archive" elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/1999/xhtml"
        schemaLocation="http://schemas.geneabase.com/2013-v1/xhtml1-reduced.xsd"/>
    <xs:import namespace="http://schemas.geneabase.com/2013-v1/geneabase"
        schemaLocation="http://schemas.geneabase.com/2013-v1/geneabase.xsd"/>
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://schemas.geneabase.com/w3c/xml.xsd"/>
    <xs:element name="archive" type="col:archiveType"/>
    <xs:element name="unit">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="col:unitType">
                    <xs:choice maxOccurs="unbounded">
                        <xs:element ref="col:unit"/>
                        <xs:element ref="col:file"/>
                    </xs:choice>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="file">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="col:unitType">
                    <xs:choice minOccurs="0">
                        <xs:element maxOccurs="unbounded" name="item" type="col:unitType"/>
                        <xs:element name="record" type="col:fileType"/>
                        <xs:element name="folder" type="col:folderType"/>
                    </xs:choice>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="col:unitType">
                    <xs:choice minOccurs="0">
                        <xs:element name="record" type="col:fileType"/>
                        <xs:element name="folder" type="col:folderType"/>
                    </xs:choice>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element abstract="false" name="summary" type="col:summaryType"/>
    <xs:element name="description" type="col:descriptionType"/>
    <xs:complexType name="archiveType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="title" type="col:titleType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="short" type="col:shortTitleType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="description"
                type="col:descriptionType"/>
            <xs:choice>
                <xs:element maxOccurs="unbounded" ref="col:unit"/>
                <xs:element maxOccurs="unbounded" ref="col:file"/>
                <xs:element ref="col:item"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="col:archiveAttributes"/>
    </xs:complexType>
    <xs:complexType name="unitType">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="title" type="col:titleType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="description"
                type="col:descriptionType"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="link" type="gb:linkType"/>
        </xs:sequence>
        <xs:attributeGroup ref="col:unitAttributes"/>
    </xs:complexType>

    <xs:simpleType name="idType">
        <xs:restriction base="xs:token">
            <xs:minLength value="1"/>
            <xs:maxLength value="36"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="unitEnumType">
        <xs:annotation>
            <xs:documentation xml:lang="en"></xs:documentation>
            <xs:documentation xml:lang="nl"></xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:enumeration value="fonds">
                <xs:annotation>
                    <xs:documentation xml:lang="en"> The fonds is generally the highest level of arrangement, and is usually used to describe the whole of the archives of an organisation or the papers of an individual.</xs:documentation>
                    <xs:documentation xml:lang="nl"></xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="sub-fonds">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Fonds may be devided into sub-fonds, generally the records of different branches of an organisation or major themes within the papers of an individual.</xs:documentation>
                    <xs:documentation xml:lang="nl"></xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="series">
                <xs:annotation>
                    <xs:documentation xml:lang="en">Series may be in a smaller archive come, either below a sub-fonds, or directly below a fonds, usually used for groupings of individual types of documents (minutes, correspondence files, deeds, etc.)</xs:documentation>
                    <xs:documentation xml:lang="nl"></xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="sub-series">
                <xs:annotation>
                    <xs:documentation xml:lang="en">A futher subdivision of series.</xs:documentation>
                    <xs:documentation xml:lang="nl"></xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="group"/>
            <xs:enumeration value="sub-group"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="archiveEnumType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="fonds"/>
            <xs:enumeration value="collection"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="titleType">
        <xs:simpleContent>
            <xs:extension base="gb:string200">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="shortTitleType">
        <xs:simpleContent>
            <xs:extension base="gb:string100">
                <xs:attribute ref="xml:lang"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="summaryType">
        <xs:complexContent>
            <xs:extension base="html:Flow">
                <xs:attribute ref="xml:lang"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="descriptionType">
        <xs:complexContent>
            <xs:extension base="html:Flow">
                <xs:attribute ref="xml:lang"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:attributeGroup name="archiveAttributes">
        <xs:attribute name="id" type="col:idType">
            <xs:annotation>
                <xs:documentation xml:lang="en">A globally unique identifier for this archive.</xs:documentation>
                <xs:documentation xml:lang="nl">Een wereldwijd unieke identifier voor deze collectie</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="gbID" type="xs:positiveInteger">
            <xs:annotation>
                <xs:documentation xml:lang="en">The internal id, to be used for Geneabase API access. This id is only for exports, and will be ignored at imports.</xs:documentation>
                <xs:documentation xml:lang="nl">De interne id, te gebruiken voor Geneabase API toegang. Deze id is alleen voor exports, en wordt genegeerd bij imports.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="localID" type="col:idType" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">A code that uniquely identifies this archive within the repository. This code is usually a more readable and memorizable than the (globally unique) id, and is used for presentation.</xs:documentation>
                <xs:documentation xml:lang="nl">Een code waarmee dit item minimaal uniek wordt aangeduid binnen de repository. Deze code is gewoonlijk beter leesbaar en onthoudbaar dan de (wereldwijd unieke) id, en wordt gebruikt in de presentatie.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" use="required" type="col:archiveEnumType"/>
        <xs:attribute name="repositoryName" type="gb:string100"/>
        <xs:attribute name="repositoryID" type="gb:uuidType" use="required"/>
        <xs:attribute ref="xml:lang"/>
        <xs:attribute name="deleted" use="optional" type="xs:boolean" default="false"/>
        <xs:attribute name="accessability" use="optional" default="restricted">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="restricted"/>
                    <xs:enumeration value="limited"/>
                    <xs:enumeration value="public"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="requestable" type="xs:boolean">
            <xs:annotation>
                <xs:documentation xml:lang="en">The default value for units for which the requestable attribute has not been specified.</xs:documentation>
                <xs:documentation xml:lang="nl">De standaard waarde voor units waarvan het "requestable" attribuut niet gespecificeerd is.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="disclosureDate" type="xs:date"/>
        <xs:attribute name="startDate" type="gb:dateType"/>
        <xs:attribute name="endDate" type="gb:dateType"/>
        <xs:attribute name="version" type="xs:dateTime" use="required"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="unitAttributes">
        <xs:attribute name="id" type="col:idType">
            <xs:annotation>
                <xs:documentation xml:lang="en">A globally unique identifier for this unit.</xs:documentation>
                <xs:documentation xml:lang="nl">Een wereldwijd unieke identifier voor deze unit.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="gbID" type="xs:positiveInteger">
            <xs:annotation>
                <xs:documentation xml:lang="en">The internal id, to be used for Geneabase API access. This id is only for exports, and will be ignored at imports.</xs:documentation>
                <xs:documentation xml:lang="nl">De interne id, te gebruiken voor Geneabase API toegang. Deze id is alleen voor exports, en wordt genegeerd bij imports.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="localID" type="col:idType" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">A code that, combined with the unit type, uniquely identifies this item within the archive. This code is usually a more readable and memorizable than the (globally unique) id, and is used for presentation.</xs:documentation>
                <xs:documentation xml:lang="nl">Een code die, gecombineerd met het unit type, dit item uniek aanduidt binnen de collectie. Deze code is gewoonlijk beter leesbaar en onthoudbaar dan de (wereldwijd unieke) id, en wordt gebruikt in de presentatie.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" use="required" type="col:unitEnumType"/>
        <xs:attribute ref="xml:lang"/>
        <xs:attribute name="accessability" use="optional" default="restricted">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="restricted"/>
                    <xs:enumeration value="limited"/>
                    <xs:enumeration value="public"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="requestable" use="optional" type="xs:boolean">
            <xs:annotation>
                <xs:documentation xml:lang="en">Specifies wether a file can be requested for digitization or not. If not specified, the default value of the parent unit applies, or else the value which is defined at the archive level. It is not needed to specify this attribute for files that already have been digitized, since it is obvious that they can no longer be requested for digitization.</xs:documentation>
                <xs:documentation xml:lang="nl">Specificeert of een file kan worden aangevraagd ter digitalisering of niet. Indien niet expliciet aangegeven, geldt als default de waarde van de parent unit, of anders de waarde die is aangegeven voor de collectie als geheel. Het is niet nodig om dit attribuut te gebruiken voor files die al gedigitaliseerd zijn, omdat het evident is dat digitalisering hiervoor niet (meer) kan worden aangevraagd.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="disclosureDate" type="xs:date"/>
        <xs:attribute name="startDate" type="gb:dateType"/>
        <xs:attribute name="endDate" type="gb:dateType"/>
    </xs:attributeGroup>
    <xs:complexType name="folderType">
        <xs:attribute name="uuid" type="gb:uuidType" use="optional"/>
        <xs:attribute name="name" type="gb:fileNameType" use="optional"/>
        <xs:attribute name="numFiles" type="xs:positiveInteger"/>
    </xs:complexType>
    <xs:complexType name="physicalUnitsType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="unit" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="meter"/>
                            <xs:enumeration value="unit"/>
                            <xs:enumeration value="book"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="fileType">
        <xs:attribute name="uuid" type="gb:uuidType" use="optional"/>
        <xs:attribute name="folder" type="gb:uuidType" use="optional"/>
        <xs:attribute name="name" type="gb:fileNameType" use="optional"/>
        <xs:attribute name="ext" type="gb:extensionType" use="optional"/>
    </xs:complexType>
</xs:schema>

=== Geneabase/Geneabase-XML/2013-v1/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:archive xmlns:gb="http://schemas.geneabase.com/2013-v1/geneabase"
 xmlns:xhtml="http://www.w3.org/1999/xhtml"
 xmlns:a="http://schemas.geneabase.com/2013-v1/archive"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://schemas.geneabase.com/2013-v1/archive file:/C:/Users/Roberto/Documents/GitHub/Geneabase-XML/2013-v1/archive.xsd" id="50" code="code0" type="fonds" version="2006-05-04T18:13:51.0Z">
    <a:title xml:lang="en-US">title0</a:title>
    <a:title xml:lang="en-US">title1</a:title>
    <a:unit type="fonds" id="50" code="code1">
        <a:file id="50" code="code2">
        </a:file>
        <a:file id="50" code="code3">
        </a:file>
    </a:unit>
    <a:unit type="fonds" id="50" code="code4">
        <a:file id="50" code="code5">
        </a:file>
        <a:file id="50" code="code6">
        </a:file>
    </a:unit>
</a:archive>
